apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  type: NodePort  # Change to LoadBalancer or ClusterIP based on your setup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000  # Change to your desired port
  
