apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    app: mongodb
spec:
  clusterIP: None  #  Makes it a headless service
  ports:
    - port: 27017
      name: mongo
  selector:
    app: mongodb
