apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP  # Internal communication only  
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  
